### ISSUE TITLE
Enhancement Request: numbers next to host/service dials

### ISSUE THREAD

**Issue by asdf1234-deleted** [mocdaniel/dashing-icinga2#102] opened 2020-03-05 14:09 UTC
![image](https://user-images.githubusercontent.com/27829577/75989280-fd064600-5ec0-11ea-885f-583b04b62fe5.png)
It's nice seeing these dials, but if we can get totals enabled or allowed, that would be nice to see, especially for large deployments. I see this works on hover-over, but making something permanent would be nice for tv displays.

**Comment by dnsmichi** [comment] 2020-03-17 21:50
This is a duplicate of #101

**Closed as completed by dnsmichi** 2020-03-17 21:50 UTC
